// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import "@/shared/lib/fontawesome";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const THEME_BRAND_INIT_SCRIPT = `
(function () {
  try {
    var root = document.documentElement;

    // bloquea transiciones al inicio
    root.classList.add("preload");

    // THEME
    var storedTheme = localStorage.getItem("theme"); // "light" | "dark" | "system"
    var systemDark = window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches;
    var useDark = storedTheme === "dark" || ((storedTheme === "system" || !storedTheme) && systemDark);

    if (useDark) root.classList.add("dark");
    else root.classList.remove("dark");

    // BRAND (zustand persist)
    var raw = localStorage.getItem("ui-preferences");
    var brand = "amber"; // tu base (naranja/ambar)

    if (raw) {
      try {
        var parsed = JSON.parse(raw);
        if (parsed && parsed.state && parsed.state.brand) brand = parsed.state.brand;
      } catch(e) {}
    }

    var map = {
      blue:  { primary: "221 83% 53%", primaryFg: "210 40% 98%" },
      green: { primary: "142 71% 45%", primaryFg: "210 40% 98%" },
      amber: { primary: "12 98% 57%",  primaryFg: "0 0% 100%" }, // ✅ naranja CILLAT
      rose:  { primary: "346 77% 49%", primaryFg: "210 40% 98%" },
    };

    var cfg = map[brand] || map.amber;
    root.style.setProperty("--primary", cfg.primary);
    root.style.setProperty("--primary-fg", cfg.primaryFg);

    // desbloquea transiciones
    requestAnimationFrame(function () {
      root.classList.remove("preload");
    });
  } catch (e) {}
})();
`;


export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <script dangerouslySetInnerHTML={{ __html: THEME_BRAND_INIT_SCRIPT }} />
            </head>

            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Providers from "@/app/providers";
// import "@/shared/lib/fontawesome";
//
//
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
//
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//
// export default function RootLayout({ children }: { children: React.ReactNode }) {
//     return (
//         <html lang="en" suppressHydrationWarning>
//             <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//                 <Providers>
//                     {children}
//                 </Providers>
//             </body>
//         </html>
//     );
// }
//
